### ISSUE TITLE
Beta upgrade: final checklist

### ISSUE THREAD

**Issue by benkeen** [formtools/core#134]
Checklist for completing the Form Tools 2 to 3 upgrade. All these tasks need to be complete before we can move the script into Beta and offer FT3 via the upgrade script.

## Core
- [x] Accommodate database changes:
>     {prefix}forms table: add_submission_button_label now "blank"
>     {prefix}modules: remove is_premium column (if defined)
>     edit_submission_onload_resources has been updated for new codemirror paths
- [x] Confirm upgrade message appears on login page. 
- [x] cache busting CSS/JS (all themes)
- [x] Core Field module? How to easily deprecate? May need a check in the FT Core. 
- [x] System Check module - everything pass?
- [x] Show invalid FT2 modules on Modules page with instructions to upgrade.
- [x] update error reporting
- [x] review open bugs and get all the important ones resolved (e.g. the image formatting of the default theme's header!)
- [x] editing checkbox Smarty content had an error in it that the new Smarty parser chokes on. Need to update that field.

## Modules
- [x] Arbitrary Settings
- [x] Client Audit
- [x] Custom Fields
- [x] Data Visualization
- [x] Export Manager
- [x] Extended Client Fields
- [x] File Upload Field
- [x] Form Backup
- [x] Form Builder
Check this one over again in more detail + provide custom instructions for anything that may potentially melt.
- [x] Google Maps Field
- [x] Hello Database!
- [x] Hello Tabs!
- [x] Hello World!
- [x] Hooks Manager
- Fiddly one. Hooks Manager will need a full mapping of old to new methods to properly upgrade.
- [x] IP Security Check
- [x] Javascript Error Logs
- [x] Pages
- [x] Report Builder
- [x] Submission Accounts
- [x] Submission History
- [x] Submission ID Manager
- [x] Submission Pre-Parser
- [x] Swift Mailer
- [x] System Check
- [x] Text Override
- [x] TinyMCE Field
Needs work too. Check out the upgrade method stub for notes.

## Upgrade script
- [x] prohibit upgrading to FT3 if ANY of the components aren't updated to the supported upgrade version (li.e. ast FT2-compatible version)
- [x] get back online

**Comment by johnbleck3** [comment]
I just updated the core with the latest files.

I got an error 
Warning: ucwords() expects exactly 1 parameter, 2 given in /var/www/forms.buffalonews.com/global/code/Modules.class.php on line 773

I changed the below for now on my installation so I can continue working on the forms.

$upper_case = ucwords($module_folder, "_");
to
$upper_case = ucwords($module_folder);

**Comment by benkeen** [comment]
Hey @johnbleck3, ah drat. I misread the docs - that second param is only available as of 5.4.32 / 5.5.16. http://php.net/manual/en/function.ucwords.php. 

I'll need to doctor this method to work on all versions of supported PHP - I'll create an issue. Thanks!

**Comment by nelsondcosta23** [comment]
Almost everything is complete :)
This will be grateful for people like me. I have 2 FT2 with a lot of information.
