### ISSUE TITLE
3.0.10 release checklist

### ISSUE THREAD

**Issue by benkeen** [formtools/core#425]
- [x] resetFieldTypes should now reset settings & setting options as well.
- [x] verify with Custom Fields 2.1.0.
- [x] Version update
- [x] Update System Check module for new database field. 
- [x] Check installation process.
